import Head from 'next/head'
import Image from 'next/image'
import Navbar from '../components/Navbar'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className="bg-blue-100 h-screen">
      <Head>
        <title>Somali North America in Tech</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <div className='pt-10 px-6'>
        <h1 className='text-2xl'>Snait - Somali North America in Tech</h1>
      </div>
    </div>
  )
}
